# FROM python:3.13.0a4-slim-bookworm
FROM python:3.8-slim-bullseye
# FROM python:3.11

COPY . .
# CMD ["python","./get-pip.py"]
# RUN pip3 install torch
RUN pip3 install cherrypy requests
RUN pip3 install python-etcd
RUN pip3 install paho-mqtt==1.6.1
CMD ["python","./main_temperature.py"]

# CMD ["bash"]